-- Migration: 002_seed_users
-- Seed tracked users
INSERT INTO tracked_users (username) VALUES
  ('AnirudhJayan083'),
  ('RAVINDRANATH_V'),
  ('Surya_5b0'),
  ('SKrishna_Pranav'),
  ('arbaz2447'),
  ('chandugeethanjali295'),
  ('ArunKumar0908'),
  ('rajini22'),
  ('DIVITE_DINESH'),
  ('Sivaram_naidu'),
  ('OjIM2Gevet'),
  ('mithulpranav24826'),
  ('_y_r_2809'),
  ('yashita-gaur'),
  ('Likitha_reddy15'),
  ('HLoqXD2QCd'),
  ('Simma_Sathwik'),
  ('pranali-123'),
  ('shahidx_05'),
  ('frikmeoe'),
  ('kesavvvvv_'),
  ('KabilanK07'),
  ('F640JVUokd'),
  ('Rahul_L_S'),
  ('065pjPjqM6'),
  ('DEEKSHITH_PEDDI'),
  ('hareesh_macha'),
  ('jaikaran109'),
  ('shemalatha331'),
  ('SWATIydv47'),
  ('duckyies'),
  ('nisthaagarwal'),
  ('youtube_aryanc403'),
  ('lee215'),
  ('shashank_ram_45'),
  ('Miha8756')
ON CONFLICT (username) DO NOTHING;
